export const QueryKeys = {
  currentUser: ['auth', 'current-user'] as const,
  settings: ['settings'] as const,
  customers: ['customers'] as const,
  customer: (id: string) => ['customers', id] as const,
  customerPets: (customerId: string) => ['pets', customerId] as const,
  pet: (id: string) => ['pets', id] as const,
  pets: ['pets'] as const,
  petVaccines: (petId: string) => ['pets', petId, 'vaccines'] as const,
  petDiseases: (petId: string) => ['pets', petId, 'diseases'] as const,
  petAllergies: (petId: string) => ['pets', petId, 'allergies'] as const,
  petWeightLogs: (petId: string) => ['pets', petId, 'weight-logs'] as const,
  appointments: ['appointments'] as const,
  appointment: (id: string) => ['appointments', id] as const,
  medicalRecords: ['medical-records'] as const,
  medicalRecord: (id: string) => ['medical-records', id] as const,
  procedures: ['procedures'] as const,
  rooms: ['rooms'] as const,
  room: (id: string) => ['rooms', id] as const,
  petHotelBookings: ['pet-hotel-bookings'] as const,
  petHotelBooking: (id: string) => ['pet-hotel-bookings', id] as const,
  petHotelLogs: (bookingId: string) => ['pet-hotel-logs', bookingId] as const,
  groomingServices: ['grooming-services'] as const,
  groomingService: (id: string) => ['grooming-services', id] as const,
  groomingBookings: ['grooming-bookings'] as const,
  groomingBooking: (id: string) => ['grooming-bookings', id] as const,
  groomingRecords: ['grooming-records'] as const,
  categories: ['categories'] as const,
  suppliers: ['suppliers'] as const,
  products: ['products'] as const,
  product: (id: string) => ['products', id] as const,
  productVariants: (productId: string) => ['products', productId, 'variants'] as const,
  productBundles: ['product-bundles'] as const,
  stockMovements: (productId: string) => ['stock-movements', productId] as const,
  lowStock: ['products', 'low-stock'] as const,
  purchaseOrders: ['purchase-orders'] as const,
  purchaseOrder: (id: string) => ['purchase-orders', id] as const,
  invoices: ['invoices'] as const,
  invoice: (id: string) => ['invoices', id] as const,
  invoiceItems: (invoiceId: string) => ['invoices', invoiceId, 'items'] as const,
  payments: (invoiceId: string) => ['payments', invoiceId] as const,
  dailySales: (date: string) => ['daily-sales', date] as const,
  cashShifts: ['cash-shifts'] as const,
  cashShift: (id: string) => ['cash-shifts', id] as const,
  activeCashShift: ['cash-shifts', 'active'] as const,
  loyaltyTiers: ['loyalty-tiers'] as const,
  loyaltyMember: (customerId: string) => ['loyalty', customerId] as const,
  loyaltyTransactions: (memberId: string) => ['loyalty-transactions', memberId] as const,
  promotions: ['promotions'] as const,
  promotion: (id: string) => ['promotions', id] as const,
  expenseCategories: ['expense-categories'] as const,
  expenses: ['expenses'] as const,
  expense: (id: string) => ['expenses', id] as const,
  feedback: (invoiceId: string) => ['feedback', invoiceId] as const,
  notifications: ['notifications'] as const,
  unreadNotifications: ['notifications', 'unread'] as const,
  auditLogs: ['audit-logs'] as const,
  users: ['users'] as const,
  user: (id: string) => ['users', id] as const,
  doctors: ['users', 'doctors'] as const,
  grooms: ['users', 'groomers'] as const,
} as const;
